name: Infra deploymment
on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy-api-dev:
    if: github.ref == 'refs/heads/dev'
    defaults:
      run:
        working-directory: ./env/dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Create Python alias
        run: |
          echo 'alias python3.11="/usr/bin/python3.11"' >> $GITHUB_ENV
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -no-color -upgrade

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Apply
        id: apply
        shell: bash
        run: |
          terraform apply -var-file="dev.tfvars" -no-color